name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Test API Key with coverage
        run: go test -v -coverprofile=coverage.out ./...
        
      - name: Show coverage
        run: go tool cover -func=coverage.out
